### ISSUE TITLE
How to use this in a workflow?

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/auto-workflow-assignment#1]
Hi,

Can you describe a bit more detailed how to use the project in practice?

I want to dynamically change the workflow assignments based on a property. Fits pretty much the described usecase. The project seems to be a good solution -  if only I would be able to understand it.
Where shall I use the Action in the example package? Where do I define the target property? Which property did you use for the test? How can I integrate this into my Workflow?

More information please! :-)

Thanks and best regards!
Angela

**Comment by EliJDonahue** [comment]
Hi Angela,

This project provides an example for a scenario when you want an end user to choose one or more identities for a task. This becomes a little more clear if you imagine that the "Workflow Assignment Example" item is a business object, like a Document. 

A user can create the business object and then set 1-3 "reviewers" in the reviewer properties. When the user saves the business object, the workflow is initialized and triggers the **labs_WorkflowAssignmentExampleCS** method. 

The **labs_WorkflowAssignmentExampleCS** method then:
* gets the business object using the **labs_GetControlledItemCSharp** method 
* builds an array of reviewers from the business object's properties
* creates an Activity Assignment for each reviewer in the array
* sets the voting weight of each assignment based on the total number of reviewers
* updates the current activity

You could easily use the sample code to allow end users to select assignees for a Part, Document, ECN, etc. You just need to add the method to an OnActivate server event on the workflow activity of your choice and update the code to get the correct properties from the business object/controlled item.

Does that make more sense?

Eli

**Comment by AngelaIp** [comment]
Thanks for the explanation!
But in the end I finally figured it out myself two weeks ago. We already use the function in one of our processes. In my variant, the respective assignments are set automatically based on the team roles and some additional properties. Much more powerful than your version :-).

**Comment by EliJDonahue** [comment]
Great idea for a project! Thanks for the follow up, Angela.
