### ISSUE TITLE
Link to icons in example workflow is corrupted

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/auto-workflow-assignment#2]
Link to icons in example workflow is corrupted:

![image](https://user-images.githubusercontent.com/32091085/35960826-7badba3e-0cab-11e8-8300-a6c0a41215aa.png)

**Comment by EliJDonahue** [comment]
Fixed! Pull/download the latest commit and it fixes the file paths.

![image](https://user-images.githubusercontent.com/6794866/36452046-fd124568-1660-11e8-8710-72438fbed75c.png)
